[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"

# NOTE: Set VITE_API_BASE_URL in Netlify UI (Site settings → Build & deploy → Environment)
  VITE_API_BASE_URL = "https://red1-1-0-0.onrender.com/api"
